### model
#model_name_or_path: E:/data/model/meta-llama/Llama-3-8B
model_name_or_path: /media/data/model/huggingface/meta-llama/Llama-3-8B-Instruct
adapter_name_or_path: saves/llama-3-8b/lora/ml-xr/pretrain
### method
# TRAINING_STAGES = {
#    "Supervised Fine-Tuning": "sft",
#    "Reward Modeling": "rm",
#    "PPO": "ppo",
#    "DPO": "dpo",
#    "KTO": "kto",
#    "Pre-Training": "pt",
#}
stage: sft # Supervised Fine-Tuning
do_train: true
finetuning_type: lora
lora_target: all

### dataset
dataset_dir: data/rec
dataset: ml-100k_ft
template: llama3 # llama3
cutoff_len: 1024
max_samples: 512
overwrite_cache: true
preprocessing_num_workers: 16

### output
output_dir: saves/llama-3-8b/lora/ml-xr/sft_512
logging_steps: 10
save_steps: 100
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: 4
gradient_accumulation_steps: 32
learning_rate: 5.0e-5
num_train_epochs: 40.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
fp16: true
ddp_timeout: 180000000

### eval
val_size: 0.1
per_device_eval_batch_size: 4
eval_strategy: steps
eval_steps: 500
